### ISSUE TITLE
new: Exponential Notation

### ISSUE THREAD

**Issue by Zaitsev** [Cominta/NerCalc#5]
Should be implemented according to 
https://en.wikipedia.org/wiki/Scientific_notation
https://www.scaler.com/topics/python-scientific-notation/

In scientific notation, nonzero numbers are written in the form

m × 10^n

3.02 × 10^3 ===  3.02**e**3
or m times ten raised to the power of n, where n is an [integer](https://en.wikipedia.org/wiki/Integer), and the [coefficient](https://en.wikipedia.org/wiki/Coefficient) m is a nonzero [real number](https://en.wikipedia.org/wiki/Real_number) (usually between 1 and 10 in absolute value, and nearly always written as a [terminating decimal](https://en.wikipedia.org/wiki/Decimal)). The integer n is called the [**exponent**](https://en.wikipedia.org/wiki/Exponent) and the real number m is called the [significand](https://en.wikipedia.org/wiki/Significand) or **mantissa**.

**Comment by Zaitsev** [comment]
Inconsistent results format
```
a=1e6
a+1=1e+06
b=1000000
b+1=1e+06
100000+1=100001
```
why some shown with `e+06` but others as `1000001`

**Comment by Zaitsev** [comment]
BUG: wrong calculations?
```
a=1e6
a+1=1e+06
b=1000000
b+1=1e+06
100000+1=100001
```
`1e6+1` is a  _1000001_ or _1.000001e6_ not `1e6`!!!

**Comment by Zaitsev** [comment]
BUG:  negative exponent  
```
1e9/1e6=1000
1e3*1e-3  #BUG
1e3=1000
1e-3 #BUG

```

**Comment by Cominta** [comment]
fixed
